-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS hangfire.aggregatedcounter
(
    id bigserial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    value bigint NOT NULL,
    expireat timestamp with time zone,
    CONSTRAINT aggregatedcounter_pkey PRIMARY KEY (id),
    CONSTRAINT aggregatedcounter_key_key UNIQUE (key)
);

CREATE TABLE IF NOT EXISTS hangfire.counter
(
    id bigserial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    value bigint NOT NULL,
    expireat timestamp with time zone,
    CONSTRAINT counter_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hangfire.hash
(
    id bigserial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    field text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default",
    expireat timestamp with time zone,
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT hash_pkey PRIMARY KEY (id),
    CONSTRAINT hash_key_field_key UNIQUE (key, field)
);

CREATE TABLE IF NOT EXISTS hangfire.job
(
    id bigserial NOT NULL,
    stateid bigint,
    statename text COLLATE pg_catalog."default",
    invocationdata jsonb NOT NULL,
    arguments jsonb NOT NULL,
    createdat timestamp with time zone NOT NULL,
    expireat timestamp with time zone,
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT job_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hangfire.jobparameter
(
    id bigserial NOT NULL,
    jobid bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default",
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT jobparameter_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hangfire.jobqueue
(
    id bigserial NOT NULL,
    jobid bigint NOT NULL,
    queue text COLLATE pg_catalog."default" NOT NULL,
    fetchedat timestamp with time zone,
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT jobqueue_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hangfire.list
(
    id bigserial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    value text COLLATE pg_catalog."default",
    expireat timestamp with time zone,
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT list_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hangfire.lock
(
    resource text COLLATE pg_catalog."default" NOT NULL,
    updatecount integer NOT NULL DEFAULT 0,
    acquired timestamp with time zone,
    CONSTRAINT lock_resource_key UNIQUE (resource)
);

CREATE TABLE IF NOT EXISTS hangfire.schema
(
    version integer NOT NULL,
    CONSTRAINT schema_pkey PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS hangfire.server
(
    id text COLLATE pg_catalog."default" NOT NULL,
    data jsonb,
    lastheartbeat timestamp with time zone NOT NULL,
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT server_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hangfire.set
(
    id bigserial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    score double precision NOT NULL,
    value text COLLATE pg_catalog."default" NOT NULL,
    expireat timestamp with time zone,
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT set_pkey PRIMARY KEY (id),
    CONSTRAINT set_key_value_key UNIQUE (key, value)
);

CREATE TABLE IF NOT EXISTS hangfire.state
(
    id bigserial NOT NULL,
    jobid bigint NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    createdat timestamp with time zone NOT NULL,
    data jsonb,
    updatecount integer NOT NULL DEFAULT 0,
    CONSTRAINT state_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."AspNetRoleClaims"
(
    "Id" serial NOT NULL,
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."AspNetRoles"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default",
    "NormalizedName" character varying(256) COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."AspNetUserClaims"
(
    "Id" serial NOT NULL,
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."AspNetUserLogins"
(
    "LoginProvider" text COLLATE pg_catalog."default" NOT NULL,
    "ProviderKey" text COLLATE pg_catalog."default" NOT NULL,
    "ProviderDisplayName" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE IF NOT EXISTS public."AspNetUserRoles"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId")
);

CREATE TABLE IF NOT EXISTS public."AspNetUserTokens"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "LoginProvider" text COLLATE pg_catalog."default" NOT NULL,
    "Name" text COLLATE pg_catalog."default" NOT NULL,
    "Value" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE TABLE IF NOT EXISTS public."AspNetUsers"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "UserName" character varying(256) COLLATE pg_catalog."default",
    "NormalizedUserName" character varying(256) COLLATE pg_catalog."default",
    "Email" character varying(256) COLLATE pg_catalog."default",
    "NormalizedEmail" character varying(256) COLLATE pg_catalog."default",
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    "SecurityStamp" text COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    "PhoneNumber" text COLLATE pg_catalog."default",
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CompanySettings"
(
    "SettingID" serial NOT NULL,
    "CompanyName" text COLLATE pg_catalog."default" NOT NULL,
    "AddressLine1" text COLLATE pg_catalog."default" NOT NULL,
    "CityStatePincode" text COLLATE pg_catalog."default" NOT NULL,
    "GracePeriodInMinutes" integer NOT NULL DEFAULT 5,
    "PayrollType" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Hourly'::text,
    "LateGraceMinutes" integer NOT NULL DEFAULT 0,
    "SalaryCalculationMethod" character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pro-Rata Hourly'::character varying,
    "ZktecoIP" character varying(50) COLLATE pg_catalog."default",
    "ZktecoPort" integer NOT NULL DEFAULT 4370,
    "ZktecoMachineNumber" integer NOT NULL DEFAULT 1,
    work_day_cutoff_hour integer NOT NULL DEFAULT 22,
    "EndTimeGraceMinutes" integer NOT NULL DEFAULT 0,
    "EnablePfEsiSystem" boolean NOT NULL DEFAULT false,
    "EmployeePfPercentage" numeric(5, 2) NOT NULL DEFAULT 12.00,
    "EmployeeEsiPercentage" numeric(5, 2) NOT NULL DEFAULT 0.75,
    "EmployerPfPercentage" numeric(5, 2) NOT NULL DEFAULT 12.00,
    "EmployerEsiPercentage" numeric(5, 2) NOT NULL DEFAULT 3.25,
    basic_salary_percentage numeric(5, 2) NOT NULL DEFAULT 40.00,
    "EsiWageLimit" numeric(10, 2) NOT NULL DEFAULT 21000.00,
    "EnableProfessionalTax" boolean NOT NULL DEFAULT false,
    "SmtpHost" text COLLATE pg_catalog."default",
    "SmtpPort" integer DEFAULT 587,
    "SmtpUser" text COLLATE pg_catalog."default",
    "SmtpPass" text COLLATE pg_catalog."default",
    "SmtpFromEmail" text COLLATE pg_catalog."default",
    "EnableEmailNotifications" boolean NOT NULL DEFAULT false,
    "EnableLeaveAccrual" boolean NOT NULL DEFAULT false,
    "LeaveAccrualRate" numeric(4, 2) NOT NULL DEFAULT 1.5,
    "EnableSandwichRule" boolean NOT NULL DEFAULT false,
    enable_shift_allowance boolean NOT NULL DEFAULT false,
    "EnableSsl" boolean DEFAULT true,
    "BasicSalaryPercentage" numeric(5, 2) NOT NULL DEFAULT 40.00,
    "EmpPFPercentage" numeric(5, 2) NOT NULL DEFAULT 12.00,
    "EmpESIPercentage" numeric(5, 2) NOT NULL DEFAULT 0.75,
    "EmployerPFPercentage" numeric(5, 2) NOT NULL DEFAULT 13.00,
    "EmployerESIPercentage" numeric(5, 2) NOT NULL DEFAULT 3.25,
    enable_tds_deduction boolean NOT NULL DEFAULT false,
    office_latitude double precision DEFAULT 0,
    office_longitude double precision DEFAULT 0,
    geo_radius_meters integer DEFAULT 100,
    CONSTRAINT "CompanySettings_pkey" PRIMARY KEY ("SettingID")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS public.attendance_regularizations
(
    regularization_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    date_of_punch date NOT NULL,
    is_in_punch boolean NOT NULL,
    punch_time_new time without time zone NOT NULL,
    reason character varying(500) COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    submission_date timestamp with time zone NOT NULL,
    approved_by_id text COLLATE pg_catalog."default",
    admin_remarks text COLLATE pg_catalog."default",
    CONSTRAINT pk_attendance_regularizations PRIMARY KEY (regularization_id)
);

CREATE TABLE IF NOT EXISTS public.attendancelogs
(
    logid serial NOT NULL,
    employeeid integer,
    biometricid character varying(50) COLLATE pg_catalog."default" NOT NULL,
    punchtime timestamp without time zone NOT NULL,
    "DeviceID" character varying(50) COLLATE pg_catalog."default",
    "LogType" character varying(20) COLLATE pg_catalog."default",
    is_approved boolean NOT NULL DEFAULT true,
    latitude double precision,
    longitude double precision,
    CONSTRAINT attendancelogs_pkey PRIMARY KEY (logid)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    logid bigserial NOT NULL,
    "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    user_id text COLLATE pg_catalog."default" NOT NULL,
    user_email text COLLATE pg_catalog."default" NOT NULL,
    action_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entity_id text COLLATE pg_catalog."default",
    details text COLLATE pg_catalog."default",
    CONSTRAINT audit_logs_pkey PRIMARY KEY (logid)
);

CREATE TABLE IF NOT EXISTS public.bonus_records
(
    bonusid serial NOT NULL,
    employeeid integer NOT NULL,
    bonus_date date NOT NULL,
    amount numeric(10, 2) NOT NULL,
    description text COLLATE pg_catalog."default",
    payrollid_paid integer,
    CONSTRAINT bonus_records_pkey PRIMARY KEY (bonusid)
);

CREATE TABLE IF NOT EXISTS public.daily_summaries
(
    summaryid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employeeid integer NOT NULL,
    shiftdate date NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    earned_standard_hours numeric NOT NULL,
    total_overtime_duration interval NOT NULL,
    total_penalty_duration interval NOT NULL,
    total_lateness interval NOT NULL,
    total_break_penalty interval NOT NULL,
    scheduled_shift_duration interval NOT NULL,
    shift_allowance_earned numeric(10, 2) DEFAULT 0,
    is_manual_override boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_daily_summaries" PRIMARY KEY (summaryid)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employeeid serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    dob date,
    role character varying(100) COLLATE pg_catalog."default",
    monthlysalary numeric(10, 2) NOT NULL,
    standardhours integer NOT NULL DEFAULT 8,
    ot_rule character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'No Overtime'::character varying,
    ot_flatrate numeric(10, 2) DEFAULT 0,
    biometricid character varying(50) COLLATE pg_catalog."default",
    standardbreakminutes integer NOT NULL DEFAULT 60,
    shiftstarttime time without time zone,
    shiftendtime time without time zone,
    "HireDate" date,
    "TerminationDate" date,
    comp_off_day integer,
    "Email" character varying(256) COLLATE pg_catalog."default",
    "SalaryCalculationMethod" text COLLATE pg_catalog."default" DEFAULT 'Hourly'::text,
    "DailyRateBasis" text COLLATE pg_catalog."default" NOT NULL DEFAULT 'ActualDaysInMonth'::text,
    "DirectHourlyWage" numeric(10, 2),
    "AnnualPaidLeaveDays" integer NOT NULL DEFAULT 12,
    "AnnualSickLeaveDays" integer NOT NULL DEFAULT 6,
    payroll_type_override character varying(50) COLLATE pg_catalog."default",
    "AspNetUserId" character varying(450) COLLATE pg_catalog."default",
    enable_pf boolean NOT NULL DEFAULT false,
    enable_esi boolean NOT NULL DEFAULT false,
    uan_number character varying(50) COLLATE pg_catalog."default",
    esi_number character varying(50) COLLATE pg_catalog."default",
    "PaidLeaveBalance" numeric(5, 2) NOT NULL DEFAULT 0,
    "SickLeaveBalance" numeric(5, 2) NOT NULL DEFAULT 0,
    "NightShiftAllowance" numeric(10, 2) DEFAULT 0,
    is_deleted boolean NOT NULL DEFAULT false,
    basic_salary_component numeric(10, 2) NOT NULL DEFAULT 0,
    hra_component numeric(10, 2) NOT NULL DEFAULT 0,
    da_component numeric(10, 2) NOT NULL DEFAULT 0,
    tds_rate_percent numeric(5, 2) NOT NULL DEFAULT 0.00,
    bank_account_number character varying(50) COLLATE pg_catalog."default",
    bank_ifsc_code character varying(20) COLLATE pg_catalog."default",
    bank_name character varying(50) COLLATE pg_catalog."default",
    enable_shift_rotation boolean NOT NULL DEFAULT false,
    rotation_group character varying(50) COLLATE pg_catalog."default",
    shift_rotation_pattern text COLLATE pg_catalog."default",
    last_rotated_date date,
    current_shift_index integer NOT NULL DEFAULT 0,
    CONSTRAINT employees_pkey PRIMARY KEY (employeeid),
    CONSTRAINT employees_biometricid_key UNIQUE (biometricid)
);

CREATE TABLE IF NOT EXISTS public.fbp_components
(
    component_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    max_annual_limit numeric NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    is_tax_exempt boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_fbp_components PRIMARY KEY (component_id)
);

CREATE TABLE IF NOT EXISTS public.feature_settings
(
    id integer NOT NULL DEFAULT 1,
    enable_payroll boolean NOT NULL DEFAULT true,
    enable_salary_advance boolean NOT NULL DEFAULT true,
    enable_shift_scheduling boolean NOT NULL DEFAULT true,
    enable_leave_management boolean NOT NULL DEFAULT true,
    enable_punch_correction boolean NOT NULL DEFAULT true,
    enable_employee_management boolean NOT NULL DEFAULT true,
    enable_company_reports boolean NOT NULL DEFAULT true,
    admin_can_view_dashboard boolean NOT NULL DEFAULT true,
    admin_can_manage_employees boolean NOT NULL DEFAULT true,
    admin_can_view_attendance boolean NOT NULL DEFAULT true,
    admin_can_run_payroll boolean NOT NULL DEFAULT false,
    admin_can_edit_settings boolean NOT NULL DEFAULT false,
    admin_can_manage_shifts boolean NOT NULL DEFAULT true,
    admin_can_view_reports boolean NOT NULL DEFAULT true,
    employee_can_view_dashboard boolean NOT NULL DEFAULT true,
    employee_can_view_payslip boolean NOT NULL DEFAULT true,
    employee_can_view_attendance boolean NOT NULL DEFAULT true,
    employee_can_view_leave boolean NOT NULL DEFAULT true,
    employee_can_view_advance boolean NOT NULL DEFAULT true,
    employee_tools_visible boolean NOT NULL DEFAULT true,
    show_theme_toggle boolean NOT NULL DEFAULT true,
    admin_can_manage_employee_permissions boolean NOT NULL DEFAULT false,
    employee_can_view_leave_history boolean NOT NULL DEFAULT true,
    enable_statutory_compliance boolean NOT NULL DEFAULT false,
    enable_professional_tax boolean NOT NULL DEFAULT false,
    enable_email_notifications boolean NOT NULL DEFAULT false,
    enable_leave_accrual boolean NOT NULL DEFAULT true,
    enable_sandwich_rule boolean NOT NULL DEFAULT false,
    enable_shift_allowance boolean NOT NULL DEFAULT false,
    enable_audit_log boolean NOT NULL DEFAULT true,
    employee_can_view_shifts boolean NOT NULL DEFAULT true,
    enable_bonus_management boolean NOT NULL DEFAULT true,
    employee_can_view_bonus boolean NOT NULL DEFAULT true,
    admin_can_manage_punch_approvals boolean NOT NULL DEFAULT true,
    enable_salary_structuring boolean NOT NULL DEFAULT false,
    enable_tds_deduction boolean NOT NULL DEFAULT false,
    enable_recycle_bin boolean NOT NULL DEFAULT false,
    enable_year_end_summary boolean NOT NULL DEFAULT true,
    enable_tax_declarations boolean NOT NULL DEFAULT false,
    enable_geo_fencing boolean NOT NULL DEFAULT false,
    enable_dual_attendance boolean NOT NULL DEFAULT false,
    enable_automatic_geofence_punching boolean NOT NULL DEFAULT false,
    enable_resignation_module boolean NOT NULL DEFAULT false,
    employee_can_view_resignation boolean NOT NULL DEFAULT true,
    employee_can_view_tax boolean NOT NULL DEFAULT true,
    enable_custom_reporting boolean NOT NULL DEFAULT false,
    enable_regularization_req boolean NOT NULL DEFAULT true,
    enable_auto_shift_rotation boolean NOT NULL DEFAULT false,
    employee_can_view_reports boolean NOT NULL DEFAULT true,
    enable_flexible_benefits boolean NOT NULL DEFAULT false,
    enable_in_app_notifications boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_feature_settings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.flexible_benefit_declarations
(
    declaration_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    financial_year integer NOT NULL,
    component_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    annual_allocated_amount numeric NOT NULL,
    monthly_allocated_amount numeric NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Draft'::character varying,
    submission_date timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    admin_remarks text COLLATE pg_catalog."default",
    CONSTRAINT pk_flexible_benefit_declarations PRIMARY KEY (declaration_id)
);

CREATE TABLE IF NOT EXISTS public.fnf_settlements
(
    settlement_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    resignation_request_id integer NOT NULL,
    settlement_date timestamp with time zone NOT NULL,
    unpaid_salary numeric(10, 2) NOT NULL DEFAULT 0,
    leave_encashment_amount numeric(10, 2) NOT NULL DEFAULT 0,
    gratuity_amount numeric(10, 2) NOT NULL DEFAULT 0,
    bonus_payable numeric(10, 2) NOT NULL DEFAULT 0,
    notice_period_recovery numeric(10, 2) NOT NULL DEFAULT 0,
    asset_recovery_cost numeric(10, 2) NOT NULL DEFAULT 0,
    outstanding_advances numeric(10, 2) NOT NULL DEFAULT 0,
    net_payable numeric(10, 2) NOT NULL DEFAULT 0,
    is_finalized boolean NOT NULL DEFAULT false,
    payment_reference text COLLATE pg_catalog."default",
    CONSTRAINT pk_fnf_settlements PRIMARY KEY (settlement_id)
);

CREATE TABLE IF NOT EXISTS public.holidays
(
    holidayid serial NOT NULL,
    holidaydate date NOT NULL,
    holidayname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT holidays_pkey PRIMARY KEY (holidayid),
    CONSTRAINT holidays_holidaydate_key UNIQUE (holidaydate)
);

CREATE TABLE IF NOT EXISTS public.leaverequests
(
    leaverequestid serial NOT NULL,
    employeeid integer NOT NULL,
    leavedate date NOT NULL,
    leavetype character varying(50) COLLATE pg_catalog."default" NOT NULL,
    isapproved boolean NOT NULL DEFAULT true,
    notes text COLLATE pg_catalog."default",
    "AdminNotes" text COLLATE pg_catalog."default",
    "Status" text COLLATE pg_catalog."default",
    is_half_day boolean NOT NULL DEFAULT false,
    CONSTRAINT leaverequests_pkey PRIMARY KEY (leaverequestid),
    CONSTRAINT leaverequests_employeeid_leavedate_key UNIQUE (employeeid, leavedate)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id text COLLATE pg_catalog."default" NOT NULL,
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    message character varying(500) COLLATE pg_catalog."default" NOT NULL,
    url character varying(255) COLLATE pg_catalog."default",
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_notifications PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.payrollhistory
(
    payrollid serial NOT NULL,
    employeeid integer NOT NULL,
    paymonth integer NOT NULL,
    payyear integer NOT NULL,
    basesalary numeric(10, 2),
    totalhoursworked numeric(5, 2),
    overtimepay numeric(10, 2),
    deductions_hours numeric(10, 2),
    deductions_advance numeric(10, 2),
    netsalary numeric(10, 2) NOT NULL,
    totalpenaltyduration interval NOT NULL DEFAULT '00:00:00'::interval,
    totalovertimeduration interval NOT NULL DEFAULT '00:00:00'::interval,
    "HourlyRate" numeric(18, 2) NOT NULL DEFAULT 0.00,
    manualleavedays integer NOT NULL DEFAULT 0,
    absentdays integer NOT NULL DEFAULT 0,
    "Bonus" numeric(10, 2) DEFAULT 0,
    basic_salary_component numeric(10, 2) DEFAULT 0,
    pf_deduction numeric(10, 2) DEFAULT 0,
    esi_deduction numeric(10, 2) DEFAULT 0,
    employer_pf_contribution numeric(10, 2) DEFAULT 0,
    employer_esi_contribution numeric(10, 2) DEFAULT 0,
    pt_deduction numeric(10, 2) DEFAULT 0,
    "TotalShiftAllowance" numeric(10, 2) DEFAULT 0,
    tds_deduction numeric(10, 2) NOT NULL DEFAULT 0.00,
    "ScheduledShiftDuration" interval,
    "TotalLateness" interval,
    "TotalBreakPenalty" interval,
    CONSTRAINT payrollhistory_pkey PRIMARY KEY (payrollid),
    CONSTRAINT payrollhistory_employeeid_paymonth_payyear_key UNIQUE (employeeid, paymonth, payyear)
);

CREATE TABLE IF NOT EXISTS public.professional_tax_slabs
(
    slab_id serial NOT NULL,
    min_salary numeric(10, 2) NOT NULL,
    max_salary numeric(10, 2) NOT NULL,
    tax_amount numeric(10, 2) NOT NULL,
    CONSTRAINT pk_pt_slabs PRIMARY KEY (slab_id)
);

CREATE TABLE IF NOT EXISTS public.report_definitions
(
    report_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    report_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    report_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    target_role character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Admin'::character varying,
    is_active boolean NOT NULL DEFAULT true,
    description character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT pk_report_definitions PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS public.resignation_requests
(
    request_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    submission_date timestamp with time zone NOT NULL,
    desired_last_working_day date NOT NULL,
    reason character varying(500) COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::text,
    approved_last_working_day date,
    admin_remarks text COLLATE pg_catalog."default",
    is_settled boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_resignation_requests PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS public.salaryadvances
(
    advanceid serial NOT NULL,
    employeeid integer NOT NULL,
    advancedate date NOT NULL,
    amount numeric(10, 2) NOT NULL,
    payrollid_paid integer,
    advancetype character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT salaryadvances_pkey PRIMARY KEY (advanceid)
);

CREATE TABLE IF NOT EXISTS public.shiftschedules
(
    scheduleid serial NOT NULL,
    employeeid integer NOT NULL,
    shiftdate date NOT NULL,
    starttime time without time zone NOT NULL,
    endtime time without time zone NOT NULL,
    is_recurring_pattern boolean NOT NULL DEFAULT false,
    pattern_duration_days integer NOT NULL DEFAULT 7,
    applies_to_day_of_week integer NOT NULL DEFAULT 0,
    CONSTRAINT shiftschedules_pkey PRIMARY KEY (scheduleid)
);

CREATE TABLE IF NOT EXISTS public.tax_declarations
(
    declaration_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    financial_year integer NOT NULL,
    regime character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'New'::character varying,
    section_80c numeric NOT NULL DEFAULT 0,
    section_80d numeric NOT NULL DEFAULT 0,
    hra_rent_paid numeric NOT NULL DEFAULT 0,
    other_exemptions numeric NOT NULL DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,
    admin_remarks text COLLATE pg_catalog."default",
    submission_date timestamp with time zone NOT NULL,
    approval_date timestamp with time zone,
    CONSTRAINT "PK_tax_declarations" PRIMARY KEY (declaration_id)
);

CREATE TABLE IF NOT EXISTS public.year_end_summaries
(
    summary_id serial NOT NULL,
    employeeid integer NOT NULL,
    tax_year integer NOT NULL,
    gross_taxable_salary numeric(18, 2) NOT NULL DEFAULT 0.00,
    total_tds_deducted numeric(18, 2) NOT NULL DEFAULT 0.00,
    total_pf_contribution_employee numeric(18, 2) NOT NULL DEFAULT 0.00,
    total_annual_absent_days integer NOT NULL DEFAULT 0,
    total_annual_ot_pay numeric(18, 2) NOT NULL DEFAULT 0.00,
    CONSTRAINT pk_year_end_summaries PRIMARY KEY (summary_id),
    CONSTRAINT uk_employeeid_taxyear UNIQUE (employeeid, tax_year)
);

ALTER TABLE IF EXISTS hangfire.jobparameter
    ADD CONSTRAINT jobparameter_jobid_fkey FOREIGN KEY (jobid)
    REFERENCES hangfire.job (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS hangfire.state
    ADD CONSTRAINT state_jobid_fkey FOREIGN KEY (jobid)
    REFERENCES hangfire.job (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_hangfire_state_jobid
    ON hangfire.state(jobid);


ALTER TABLE IF EXISTS public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
    REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId"
    ON public."AspNetRoleClaims"("RoleId");


ALTER TABLE IF EXISTS public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId"
    ON public."AspNetUserClaims"("UserId");


ALTER TABLE IF EXISTS public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId"
    ON public."AspNetUserLogins"("UserId");


ALTER TABLE IF EXISTS public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
    REFERENCES public."AspNetRoles" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId"
    ON public."AspNetUserRoles"("RoleId");


ALTER TABLE IF EXISTS public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."AspNetUsers" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attendancelogs
    ADD CONSTRAINT attendancelogs_employeeid_fkey FOREIGN KEY (employeeid)
    REFERENCES public.employees (employeeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bonus_records
    ADD CONSTRAINT bonus_employee_fkey FOREIGN KEY (employeeid)
    REFERENCES public.employees (employeeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.leaverequests
    ADD CONSTRAINT leaverequests_employeeid_fkey FOREIGN KEY (employeeid)
    REFERENCES public.employees (employeeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payrollhistory
    ADD CONSTRAINT payrollhistory_employeeid_fkey FOREIGN KEY (employeeid)
    REFERENCES public.employees (employeeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.salaryadvances
    ADD CONSTRAINT salaryadvances_employeeid_fkey FOREIGN KEY (employeeid)
    REFERENCES public.employees (employeeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.year_end_summaries
    ADD CONSTRAINT fk_employeeid FOREIGN KEY (employeeid)
    REFERENCES public.employees (employeeid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;