package com.biometric.app.ui

import android.app.DatePickerDialog
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.biometric.app.R
import com.biometric.app.api.AdminShiftDto
import com.biometric.app.data.MainRepository
import com.biometric.app.sync.FirebaseSyncManager
import com.biometric.app.databinding.ActivityShiftManagerBinding
import com.biometric.app.databinding.DialogAddShiftBinding
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.launch
import java.util.*
import javax.inject.Inject

@AndroidEntryPoint
class ShiftManagerActivity : AppCompatActivity() {
    @Inject lateinit var firebaseSync: FirebaseSyncManager
    @Inject lateinit var repository: MainRepository
    private lateinit var binding: ActivityShiftManagerBinding
    private val rows = mutableListOf<AdminShiftDto>()
    private var shiftsJob: Job? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityShiftManagerBinding.inflate(layoutInflater); setContentView(binding.root)
        setSupportActionBar(binding.toolbar); binding.toolbar.setNavigationOnClickListener { finish() }
        binding.rvShifts.layoutManager = LinearLayoutManager(this); binding.rvShifts.adapter = ShiftAdapter()
        binding.fabAdd.setOnClickListener { showAddShiftDialog() }
        binding.btnGenerate.setOnClickListener { generateShifts() }
        observeShifts()
    }

    private fun observeShifts() {
        shiftsJob?.cancel()
        shiftsJob = lifecycleScope.launch {
            firebaseSync.observeShiftSchedules().collectLatest { remoteRows ->
                val names = repository.allEmployeesFlow.value
                    .associate { it.employeeId.toIntOrNull() ?: 0 to it.name }

                val mapped = remoteRows.map {
                    AdminShiftDto(
                        id = it.scheduleId,
                        employeeId = it.employeeId,
                        employeeName = names[it.employeeId] ?: "Employee #${it.employeeId}",
                        shiftDate = it.shiftDate,
                        startTime = it.startTime,
                        endTime = it.endTime,
                        isRecurringPattern = it.isRecurringPattern,
                        patternDurationDays = it.patternDurationDays,
                        dayOfWeek = it.appliesToDayOfWeek
                    )
                }

                rows.clear()
                rows.addAll(mapped)
                binding.rvShifts.adapter?.notifyDataSetChanged()
            }
        }
    }

    private fun generateShifts() = lifecycleScope.launch {
        val count = firebaseSync.generateShiftSchedulesFromPatterns()
        toast(if (count > 0) "$count shifts generated for the next 30 days 📅✅"
              else "No new shifts were generated. Check recurring patterns or existing schedules.")
    }

    private fun showAddShiftDialog() {
        val d = DialogAddShiftBinding.inflate(LayoutInflater.from(this))
        val employees = repository.allEmployeesFlow.value.filter { !it.isDeleted }.sortedBy { it.name }
        d.etName.setText(employees.firstOrNull()?.employeeId?.toString().orEmpty())
        d.etDate.setText(String.format(Locale.US, "%tF", Date()))
        d.etDate.setOnClickListener { pickDate(d.etDate) }
        MaterialAlertDialogBuilder(this).setTitle("Schedule Employee Shift 🕒📅")
            .setMessage("Enter the Employee ID, date and shift times. Recurring patterns are generated by the Web rostering engine.")
            .setView(d.root)
            .setPositiveButton("Save") { _, _ ->
                val employeeId = d.etName.text.toString().toIntOrNull() ?: 0
                val date = d.etDate.text.toString()
                val start = d.etStart.text.toString().trim()
                val end = d.etEnd.text.toString().trim()
                val recurring = d.cbRecurring.isChecked
                val duration = d.etDuration.text.toString().toIntOrNull() ?: 7
                if (employeeId <= 0 || date.isBlank() || start.isBlank() || end.isBlank()) { toast("Employee, date and times are required ⚠️"); return@setPositiveButton }
                lifecycleScope.launch {
                    val id = (rows.maxOfOrNull { it.id } ?: 0) + 1
                    val day = runCatching { java.time.LocalDate.parse(date).dayOfWeek.value % 7 }.getOrDefault(0)
                    val record = FirebaseSyncManager.ShiftScheduleRecord(
                        scheduleId = id,
                        employeeId = employeeId,
                        shiftDate = if (recurring) {
                            runCatching {
                                java.time.LocalDate.parse(date)
                                    .minusDays(java.time.LocalDate.parse(date).dayOfWeek.value.toLong() % 7)
                                    .toString()
                            }.getOrDefault(date)
                        } else date,
                        startTime = if (start.length == 5) "$start:00" else start,
                        endTime = if (end.length == 5) "$end:00" else end,
                        isRecurringPattern = recurring,
                        patternDurationDays = duration,
                        appliesToDayOfWeek = day
                    )
                    if (firebaseSync.pushShiftSchedule(record))
                        toast("Shift scheduled successfully ✅")
                    else
                        toast("Unable to save shift to Firebase ⚠️")
                }
            }.setNegativeButton("Cancel", null).show()
    }

    private fun pickDate(target: EditText) { val c=Calendar.getInstance(); DatePickerDialog(this,{_,y,m,day->target.setText(String.format(Locale.US,"%04d-%02d-%02d",y,m+1,day))},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show() }
    private fun deleteShift(row: AdminShiftDto) =
        MaterialAlertDialogBuilder(this)
            .setTitle("Delete Shift 🗑️")
            .setMessage("Delete ${row.employeeName}'s ${row.shiftDate} shift?")
            .setPositiveButton("Delete") { _, _ ->
                lifecycleScope.launch {
                    if (firebaseSync.deleteShiftSchedule(row.id))
                        toast("Shift deleted 🗑️")
                    else
                        toast("Unable to delete shift from Firebase ⚠️")
                }
            }
            .setNegativeButton("Cancel", null)
            .show()
    override fun onDestroy() {
        shiftsJob?.cancel()
        super.onDestroy()
    }

    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()

    inner class ShiftAdapter : RecyclerView.Adapter<ShiftAdapter.VH>() {
        override fun onCreateViewHolder(p:ViewGroup,t:Int)=VH(LayoutInflater.from(p.context).inflate(R.layout.item_shift_card,p,false))
        override fun getItemCount()=rows.size
        override fun onBindViewHolder(h:VH,pos:Int){ val x=rows[pos]; h.v.findViewById<TextView>(R.id.tvName).text="👤 ${x.employeeName}"; h.v.findViewById<TextView>(R.id.tvDetails).text="📅 ${x.shiftDate}  •  🕒 ${x.startTime} - ${x.endTime}"; h.v.findViewById<View>(R.id.btnDelete).setOnClickListener{deleteShift(x)}; h.v.setOnClickListener{} }
        inner class VH(val v:View):RecyclerView.ViewHolder(v)
    }
}
