from pathlib import Path
root=Path('/mnt/data/work1100g')
# LiveStaffLocationPanel
p=root/'Web/Payroll.Web/Components/UI/Attendance/LiveStaffLocationPanel.razor'; s=p.read_text()
s=s.replace('@inject IDbContextFactory<AppDbContext> DbFactory\n', '@inject IDbContextFactory<AppDbContext> DbFactory\n@inject FirebaseEmployeeManagementService FirebaseEmployees\n')
old='''            var data =\n                await db.Employees\n                    .AsNoTracking()\n                    .Where(e =>\n                        !e.TerminationDate.HasValue)\n                    .OrderBy(e => e.Name)\n                    .ToListAsync();'''
new='''            var data =\n                (await FirebaseEmployees.GetEmployeesAsync())\n                    .Where(e => !e.IsDeleted && !e.TerminateDate.HasValue)\n                    .OrderBy(e => e.Name)\n                    .ToList();'''
s=s.replace(old,new)
old='''                var activeSessions = await (\n                    from session in db.EmployeeGpsSessions.AsNoTracking()\n                    join employee in db.Employees.AsNoTracking()\n                        on session.EmployeeId equals employee.EmployeeID\n                    where employeeIds.Contains(session.EmployeeId)\n                          && !employee.IsDeleted\n                          && !session.EndedAtUtc.HasValue\n                          && session.LastLatitude.HasValue\n                          && session.LastLongitude.HasValue\n                    orderby session.EmployeeId, session.StartedAtUtc descending\n                    select session)\n                    .ToListAsync();'''
new='''                var activeSessions = await db.EmployeeGpsSessions.AsNoTracking()\n                    .Where(session => employeeIds.Contains(session.EmployeeId)\n                          && !session.EndedAtUtc.HasValue\n                          && session.LastLatitude.HasValue\n                          && session.LastLongitude.HasValue)\n                    .OrderBy(session => session.EmployeeId)\n                    .ThenByDescending(session => session.StartedAtUtc)\n                    .ToListAsync();'''
s=s.replace(old,new)
p.write_text(s)

# OfflineTrackingDetails
p=root/'Web/Payroll.Web/Components/Pages/Admin/OfflineTrackingDetails.razor'; s=p.read_text()
s=s.replace('@inject IDbContextFactory<AppDbContext> DbFactory\n', '@inject IDbContextFactory<AppDbContext> DbFactory\n@inject FirebaseEmployeeManagementService FirebaseEmployees\n')
old='''            employees = await db.Employees.AsNoTracking()\n                .Where(x => !x.IsDeleted)\n                .OrderBy(x => x.Name)\n                .Select(x => new EmployeeOption { EmployeeID = x.EmployeeID, Name = x.Name })\n                .ToListAsync();'''
new='''            employees = (await FirebaseEmployees.GetEmployeesAsync())\n                .Where(x => !x.IsDeleted)\n                .OrderBy(x => x.Name)\n                .Select(x => new EmployeeOption { EmployeeID = x.EmployeeID, Name = x.Name })\n                .ToList();'''
s=s.replace(old,new)
old='''            var rawPoints = await (from p in historyQuery\n                                   join e in db.Employees.AsNoTracking() on p.EmployeeId equals e.EmployeeID\n                                   orderby p.CapturedAtUtc ascending\n                                   select new PointRow\n                                   {\n                                       EmployeeId = p.EmployeeId, EmployeeName = e.Name, SessionId = p.SessionId,\n                                       Latitude = p.Latitude, Longitude = p.Longitude, AccuracyMeters = p.AccuracyMeters,\n                                       DistanceMeters = p.DistanceFromOfficeMeters, RadiusMeters = p.AllowedRadiusMeters,\n                                       WithinRadius = p.IsWithinAllowedRadius, CapturedAtUtc = p.CapturedAtUtc,\n                                       CaptureSource = p.CaptureSource, SyncBatchId = p.SyncBatchId, SyncedAtUtc = p.SyncedAtUtc,\n                                       RecordedAtUtc = p.RecordedAtUtc\n                                   }).Take(2000).ToListAsync();\n\n            points = BuildPointRows(rawPoints);'''
new='''            var rawPoints = await historyQuery\n                .OrderBy(p => p.CapturedAtUtc)\n                .Take(2000)\n                .Select(p => new PointRow\n                {\n                    EmployeeId = p.EmployeeId, EmployeeName = string.Empty, SessionId = p.SessionId,\n                    Latitude = p.Latitude, Longitude = p.Longitude, AccuracyMeters = p.AccuracyMeters,\n                    DistanceMeters = p.DistanceFromOfficeMeters, RadiusMeters = p.AllowedRadiusMeters,\n                    WithinRadius = p.IsWithinAllowedRadius, CapturedAtUtc = p.CapturedAtUtc,\n                    CaptureSource = p.CaptureSource, SyncBatchId = p.SyncBatchId, SyncedAtUtc = p.SyncedAtUtc,\n                    RecordedAtUtc = p.RecordedAtUtc\n                }).ToListAsync();\n\n            var employeeNames = employees.ToDictionary(x => x.EmployeeID, x => x.Name);\n            foreach (var point in rawPoints)\n                point.EmployeeName = employeeNames.GetValueOrDefault(point.EmployeeId, $"Employee #{point.EmployeeId}");\n\n            points = BuildPointRows(rawPoints);'''
s=s.replace(old,new)
old='''            var rawSessions = await (from s in sessionQuery\n                                     join e in db.Employees.AsNoTracking() on s.EmployeeId equals e.EmployeeID\n                                     where s.StartedAtUtc < toUtc &&\n                                           (s.EndedAtUtc == null || s.EndedAtUtc >= fromUtc)\n                                     orderby s.StartedAtUtc descending\n                                     select new SessionRow\n                                     {\n                                         EmployeeId = s.EmployeeId, EmployeeName = e.Name, SessionId = s.SessionId,\n                                         StartedUtc = s.StartedAtUtc, LastUpdateUtc = s.LastUpdateAtUtc,\n                                         EndedUtc = s.EndedAtUtc, EndReason = s.EndReason,\n                                         TotalPoints = s.TotalPoints, TotalDistanceMeters = s.TotalDistanceMeters\n                                     }).Take(500).ToListAsync();\n\n            sessions = rawSessions;'''
new='''            var rawSessions = await sessionQuery\n                .Where(s => s.StartedAtUtc < toUtc &&\n                            (s.EndedAtUtc == null || s.EndedAtUtc >= fromUtc))\n                .OrderByDescending(s => s.StartedAtUtc)\n                .Take(500)\n                .Select(s => new SessionRow\n                {\n                    EmployeeId = s.EmployeeId, EmployeeName = string.Empty, SessionId = s.SessionId,\n                    StartedUtc = s.StartedAtUtc, LastUpdateUtc = s.LastUpdateAtUtc,\n                    EndedUtc = s.EndedAtUtc, EndReason = s.EndReason,\n                    TotalPoints = s.TotalPoints, TotalDistanceMeters = s.TotalDistanceMeters\n                }).ToListAsync();\n\n            foreach (var session in rawSessions)\n                session.EmployeeName = employeeNames.GetValueOrDefault(session.EmployeeId, $"Employee #{session.EmployeeId}");\n\n            sessions = rawSessions;'''
s=s.replace(old,new)
p.write_text(s)

# OfflineTracking page already uses Firebase for employee list but joins; replace join with dictionary post-query
p=root/'Web/Payroll.Web/Components/Pages/Admin/OfflineTracking.razor'; s=p.read_text()
old='''            offlineSyncRows = await (from point in db.EmployeeLocationHistory.AsNoTracking()\n                                      join employee in db.Employees.AsNoTracking() on point.EmployeeId equals employee.EmployeeID\n                                      where point.CaptureSource == "OfflineSync" &&\n                                            point.CapturedAtUtc >= DateTime.UtcNow.Date\n                                      orderby point.CapturedAtUtc descending\n                                      select new OfflineSyncRow\n                                      {\n                                          EmployeeName = employee.Name,\n                                          CapturedAtUtc = point.CapturedAtUtc,\n                                          SyncedAtUtc = point.SyncedAtUtc,\n                                          IsWithinAllowedRadius = point.IsWithinAllowedRadius,\n                                          Latitude = point.Latitude,\n                                          Longitude = point.Longitude\n                                      }).Take(500).ToListAsync();'''
new='''            offlineSyncRows = await db.EmployeeLocationHistory.AsNoTracking()\n                .Where(point => point.CaptureSource == "OfflineSync" &&\n                                point.CapturedAtUtc >= DateTime.UtcNow.Date)\n                .OrderByDescending(point => point.CapturedAtUtc)\n                .Take(500)\n                .Select(point => new OfflineSyncRow\n                {\n                    EmployeeName = string.Empty,\n                    CapturedAtUtc = point.CapturedAtUtc,\n                    SyncedAtUtc = point.SyncedAtUtc,\n                    IsWithinAllowedRadius = point.IsWithinAllowedRadius,\n                    Latitude = point.Latitude,\n                    Longitude = point.Longitude,\n                    EmployeeId = point.EmployeeId\n                }).ToListAsync();\n\n            var employeeNames = employeeList.ToDictionary(x => x.EmployeeID, x => x.Name);\n            foreach (var row in offlineSyncRows)\n                row.EmployeeName = employeeNames.GetValueOrDefault(row.EmployeeId, $"Employee #{row.EmployeeId}");'''
s=s.replace(old,new)
p.write_text(s)
