CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE attendance_regularizations (
        regularization_id integer GENERATED BY DEFAULT AS IDENTITY,
        employee_id integer NOT NULL,
        date_of_punch date NOT NULL,
        is_in_punch boolean NOT NULL,
        punch_time_new time without time zone NOT NULL,
        reason character varying(500) NOT NULL,
        status character varying(20) NOT NULL,
        submission_date timestamp without time zone NOT NULL,
        approved_by_id text,
        admin_remarks text,
        CONSTRAINT "PK_attendance_regularizations" PRIMARY KEY (regularization_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE attendancelogs (
        logid integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer,
        biometricid text NOT NULL,
        punchtime timestamp without time zone NOT NULL,
        "DeviceID" character varying(50),
        "LogType" character varying(20),
        is_approved boolean NOT NULL,
        latitude double precision,
        longitude double precision,
        CONSTRAINT "PK_attendancelogs" PRIMARY KEY (logid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE audit_logs (
        logid bigint GENERATED BY DEFAULT AS IDENTITY,
        timestamp timestamp without time zone NOT NULL,
        user_id text NOT NULL,
        user_email text NOT NULL,
        action_type character varying(50) NOT NULL,
        entity_type character varying(100) NOT NULL,
        entity_id text,
        details text,
        CONSTRAINT "PK_audit_logs" PRIMARY KEY (logid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE bonus_records (
        bonusid integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer NOT NULL,
        bonus_date timestamp without time zone NOT NULL,
        amount numeric NOT NULL,
        description text,
        payrollid_paid integer,
        CONSTRAINT "PK_bonus_records" PRIMARY KEY (bonusid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE public."CompanySettings" (
        "SettingID" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyName" text NOT NULL,
        "AddressLine1" text NOT NULL,
        "CityStatePincode" text NOT NULL,
        "SalaryCalculationMethod" text NOT NULL,
        "ZktecoIP" character varying(50),
        "ZktecoPort" integer NOT NULL,
        "ZktecoMachineNumber" integer NOT NULL,
        work_day_cutoff_hour integer NOT NULL,
        "EndTimeGraceMinutes" integer NOT NULL,
        "LateGraceMinutes" integer NOT NULL,
        "EnablePfEsiSystem" boolean NOT NULL,
        "EsiWageLimit" numeric NOT NULL,
        basic_salary_percentage numeric NOT NULL,
        "EmployeePfPercentage" numeric NOT NULL,
        "EmployeeEsiPercentage" numeric NOT NULL,
        "EmployerPfPercentage" numeric NOT NULL,
        "EmployerEsiPercentage" numeric NOT NULL,
        "EnableProfessionalTax" boolean NOT NULL,
        "EnableEmailNotifications" boolean NOT NULL,
        "SmtpHost" text,
        "SmtpPort" integer NOT NULL,
        "SmtpUser" text,
        "SmtpPass" text,
        "SmtpFromEmail" text,
        "EnableSsl" boolean NOT NULL,
        enable_shift_allowance boolean NOT NULL,
        "EnableLeaveAccrual" boolean NOT NULL,
        "LeaveAccrualRate" numeric NOT NULL,
        "EnableSandwichRule" boolean NOT NULL,
        enable_leave_management boolean NOT NULL,
        enable_tds_deduction boolean NOT NULL,
        office_latitude double precision NOT NULL,
        office_longitude double precision NOT NULL,
        geo_radius_meters integer NOT NULL,
        CONSTRAINT "PK_CompanySettings" PRIMARY KEY ("SettingID")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE daily_summaries (
        summaryid integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer NOT NULL,
        shiftdate date NOT NULL,
        status character varying(50) NOT NULL,
        earned_standard_hours numeric NOT NULL,
        total_overtime_duration interval NOT NULL,
        total_penalty_duration interval NOT NULL,
        total_lateness interval NOT NULL,
        total_break_penalty interval NOT NULL,
        scheduled_shift_duration interval NOT NULL,
        shift_allowance_earned numeric NOT NULL,
        is_manual_override boolean NOT NULL,
        CONSTRAINT "PK_daily_summaries" PRIMARY KEY (summaryid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE public.employees (
        employeeid integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        dob date,
        role character varying(100),
        monthlysalary numeric NOT NULL,
        basic_salary_component numeric NOT NULL,
        hra_component numeric NOT NULL,
        da_component numeric NOT NULL,
        standardhours integer NOT NULL,
        ot_rule character varying(20) NOT NULL,
        ot_flatrate numeric NOT NULL,
        biometricid character varying(50),
        standardbreakminutes integer NOT NULL,
        shiftstarttime time without time zone,
        shiftendtime time without time zone,
        "HireDate" date,
        "TerminationDate" date,
        comp_off_day integer,
        "Email" character varying(256),
        payroll_type_override character varying(50),
        "SalaryCalculationMethod" character varying(50),
        "DirectHourlyWage" numeric,
        "AspNetUserId" character varying(450),
        enable_pf boolean NOT NULL,
        enable_esi boolean NOT NULL,
        uan_number text,
        esi_number text,
        "PaidLeaveBalance" numeric NOT NULL,
        "SickLeaveBalance" numeric NOT NULL,
        "NightShiftAllowance" numeric NOT NULL,
        tds_rate_percent numeric NOT NULL,
        is_deleted boolean NOT NULL,
        bank_account_number character varying(50),
        bank_ifsc_code character varying(20),
        bank_name character varying(50),
        enable_shift_rotation boolean NOT NULL,
        rotation_group text,
        shift_rotation_pattern text,
        last_rotated_date date,
        current_shift_index integer NOT NULL,
        CONSTRAINT "PK_employees" PRIMARY KEY (employeeid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE fbp_components (
        component_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(50) NOT NULL,
        max_annual_limit numeric NOT NULL,
        is_active boolean NOT NULL,
        is_tax_exempt boolean NOT NULL,
        CONSTRAINT "PK_fbp_components" PRIMARY KEY (component_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE feature_settings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        enable_payroll boolean NOT NULL,
        enable_salary_advance boolean NOT NULL,
        enable_bonus_management boolean NOT NULL,
        enable_salary_structuring boolean NOT NULL,
        employee_can_view_advance boolean NOT NULL,
        employee_can_view_bonus boolean NOT NULL,
        enable_tds_deduction boolean NOT NULL,
        enable_shift_scheduling boolean NOT NULL,
        enable_leave_management boolean NOT NULL,
        enable_punch_correction boolean NOT NULL,
        enable_employee_management boolean NOT NULL,
        enable_company_reports boolean NOT NULL,
        enable_statutory_compliance boolean NOT NULL,
        admin_can_view_dashboard boolean NOT NULL,
        admin_can_manage_employees boolean NOT NULL,
        admin_can_view_attendance boolean NOT NULL,
        admin_can_run_payroll boolean NOT NULL,
        admin_can_edit_settings boolean NOT NULL,
        admin_can_manage_shifts boolean NOT NULL,
        admin_can_manage_punch_approvals boolean NOT NULL,
        admin_can_view_reports boolean NOT NULL,
        employee_can_view_dashboard boolean NOT NULL,
        employee_can_view_payslip boolean NOT NULL,
        employee_can_view_attendance boolean NOT NULL,
        employee_can_view_leave boolean NOT NULL,
        employee_can_view_leave_history boolean NOT NULL,
        employee_tools_visible boolean NOT NULL,
        show_theme_toggle boolean NOT NULL,
        admin_can_manage_employee_permissions boolean NOT NULL,
        enable_professional_tax boolean NOT NULL,
        enable_email_notifications boolean NOT NULL,
        enable_leave_accrual boolean NOT NULL,
        enable_sandwich_rule boolean NOT NULL,
        enable_shift_allowance boolean NOT NULL,
        enable_audit_log boolean NOT NULL,
        employee_can_view_shifts boolean NOT NULL,
        enable_year_end_summary boolean NOT NULL,
        enable_recycle_bin boolean NOT NULL,
        enable_tax_declarations boolean NOT NULL,
        enable_geo_fencing boolean NOT NULL,
        enable_resignation_module boolean NOT NULL,
        employee_can_view_resignation boolean NOT NULL,
        employee_can_view_tax boolean NOT NULL,
        enable_custom_reporting boolean NOT NULL,
        employee_can_view_reports boolean NOT NULL,
        enable_regularization_req boolean NOT NULL,
        enable_auto_shift_rotation boolean NOT NULL,
        enable_flexible_benefits boolean NOT NULL,
        enable_in_app_notifications boolean NOT NULL,
        CONSTRAINT "PK_feature_settings" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE flexible_benefit_declarations (
        declaration_id integer GENERATED BY DEFAULT AS IDENTITY,
        employee_id integer NOT NULL,
        financial_year integer NOT NULL,
        component_name character varying(100) NOT NULL,
        annual_allocated_amount numeric NOT NULL,
        monthly_allocated_amount numeric NOT NULL,
        status character varying(20) NOT NULL,
        submission_date timestamp without time zone NOT NULL,
        is_active boolean NOT NULL,
        admin_remarks text,
        CONSTRAINT "PK_flexible_benefit_declarations" PRIMARY KEY (declaration_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE fnf_settlements (
        settlement_id integer GENERATED BY DEFAULT AS IDENTITY,
        employee_id integer NOT NULL,
        resignation_request_id integer NOT NULL,
        settlement_date timestamp without time zone NOT NULL,
        unpaid_salary numeric NOT NULL,
        leave_encashment_amount numeric NOT NULL,
        gratuity_amount numeric NOT NULL,
        bonus_payable numeric NOT NULL,
        notice_period_recovery numeric NOT NULL,
        asset_recovery_cost numeric NOT NULL,
        outstanding_advances numeric NOT NULL,
        net_payable numeric NOT NULL,
        is_finalized boolean NOT NULL,
        payment_reference text,
        CONSTRAINT "PK_fnf_settlements" PRIMARY KEY (settlement_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE public.holidays (
        holidayid integer GENERATED BY DEFAULT AS IDENTITY,
        holidaydate date NOT NULL,
        holidayname character varying(100) NOT NULL,
        CONSTRAINT "PK_holidays" PRIMARY KEY (holidayid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE leaverequests (
        leaverequestid integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer NOT NULL,
        leavedate timestamp without time zone,
        leavetype text NOT NULL,
        is_half_day boolean NOT NULL,
        isapproved boolean NOT NULL,
        notes text,
        CONSTRAINT "PK_leaverequests" PRIMARY KEY (leaverequestid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE notifications (
        notification_id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id text NOT NULL,
        title character varying(100) NOT NULL,
        message character varying(500) NOT NULL,
        url character varying(255),
        is_read boolean NOT NULL,
        created_at timestamp without time zone NOT NULL,
        CONSTRAINT "PK_notifications" PRIMARY KEY (notification_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE payrollhistory (
        payrollid integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer NOT NULL,
        paymonth integer NOT NULL,
        payyear integer NOT NULL,
        "TotalLateness" interval,
        "TotalBreakPenalty" interval,
        "ScheduledShiftDuration" interval,
        basesalary numeric,
        totalhoursworked numeric,
        overtimepay numeric,
        deductions_hours numeric,
        deductions_advance numeric,
        "Bonus" numeric,
        netsalary numeric NOT NULL,
        manualleavedays integer NOT NULL,
        absentdays integer NOT NULL,
        totalpenaltyduration interval NOT NULL,
        totalovertimeduration interval NOT NULL,
        "HourlyRate" numeric NOT NULL,
        basic_salary_component numeric NOT NULL,
        pf_deduction numeric NOT NULL,
        esi_deduction numeric NOT NULL,
        employer_pf_contribution numeric NOT NULL,
        employer_esi_contribution numeric NOT NULL,
        pt_deduction numeric NOT NULL,
        tds_deduction numeric NOT NULL,
        "TotalShiftAllowance" numeric NOT NULL,
        CONSTRAINT "PK_payrollhistory" PRIMARY KEY (payrollid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE professional_tax_slabs (
        slab_id integer GENERATED BY DEFAULT AS IDENTITY,
        min_salary numeric NOT NULL,
        max_salary numeric NOT NULL,
        tax_amount numeric NOT NULL,
        CONSTRAINT "PK_professional_tax_slabs" PRIMARY KEY (slab_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE report_definitions (
        report_id integer GENERATED BY DEFAULT AS IDENTITY,
        report_name character varying(100) NOT NULL,
        report_type character varying(50) NOT NULL,
        target_role character varying(50) NOT NULL,
        is_active boolean NOT NULL,
        description character varying(255) NOT NULL,
        CONSTRAINT "PK_report_definitions" PRIMARY KEY (report_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE resignation_requests (
        request_id integer GENERATED BY DEFAULT AS IDENTITY,
        employee_id integer NOT NULL,
        submission_date timestamp without time zone NOT NULL,
        desired_last_working_day date NOT NULL,
        reason character varying(500) NOT NULL,
        status text NOT NULL,
        approved_last_working_day date,
        admin_remarks text,
        is_settled boolean NOT NULL,
        CONSTRAINT "PK_resignation_requests" PRIMARY KEY (request_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE salaryadvances (
        advanceid integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer NOT NULL,
        advancedate timestamp without time zone,
        amount numeric NOT NULL,
        advancetype text,
        payrollid_paid integer,
        CONSTRAINT "PK_salaryadvances" PRIMARY KEY (advanceid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE shiftschedules (
        scheduleid integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer NOT NULL,
        shiftdate date NOT NULL,
        starttime time without time zone NOT NULL,
        endtime time without time zone NOT NULL,
        is_recurring_pattern boolean NOT NULL,
        pattern_duration_days integer NOT NULL,
        applies_to_day_of_week integer NOT NULL,
        CONSTRAINT "PK_shiftschedules" PRIMARY KEY (scheduleid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE tax_declarations (
        declaration_id integer GENERATED BY DEFAULT AS IDENTITY,
        employee_id integer NOT NULL,
        financial_year integer NOT NULL,
        regime character varying(10) NOT NULL,
        section_80c numeric NOT NULL,
        section_80d numeric NOT NULL,
        hra_rent_paid numeric NOT NULL,
        other_exemptions numeric NOT NULL,
        status character varying(20) NOT NULL,
        admin_remarks text,
        submission_date timestamp without time zone NOT NULL,
        approval_date timestamp without time zone,
        CONSTRAINT "PK_tax_declarations" PRIMARY KEY (declaration_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE year_end_summaries (
        summary_id integer GENERATED BY DEFAULT AS IDENTITY,
        employeeid integer NOT NULL,
        tax_year integer NOT NULL,
        gross_taxable_salary numeric NOT NULL,
        total_tds_deducted numeric NOT NULL,
        total_pf_contribution_employee numeric NOT NULL,
        total_annual_absent_days integer NOT NULL,
        total_annual_ot_pay numeric NOT NULL,
        CONSTRAINT "PK_year_end_summaries" PRIMARY KEY (summary_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251205105717_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251205105717_InitialCreate', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260821131159_AddEmployeeLocationHistory') THEN
    CREATE TABLE employee_location_history (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "EmployeeId" integer NOT NULL,
        "SessionId" uuid NOT NULL,
        "Latitude" double precision NOT NULL,
        "Longitude" double precision NOT NULL,
        "DistanceFromOfficeMeters" double precision NOT NULL,
        "AllowedRadiusMeters" integer NOT NULL,
        "IsWithinAllowedRadius" boolean NOT NULL,
        "RecordedAtUtc" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_employee_location_history" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260821131159_AddEmployeeLocationHistory') THEN
    CREATE INDEX "IX_employee_location_history_EmployeeId_RecordedAtUtc" ON employee_location_history ("EmployeeId", "RecordedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260821131159_AddEmployeeLocationHistory') THEN
    CREATE INDEX "IX_employee_location_history_SessionId_RecordedAtUtc" ON employee_location_history ("SessionId", "RecordedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260821131159_AddEmployeeLocationHistory') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260821131159_AddEmployeeLocationHistory', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822074029_AddGeoPunchAudits') THEN
    CREATE TABLE geo_punch_audits (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        employee_id integer NOT NULL,
        session_id uuid,
        punch_time_utc timestamp without time zone NOT NULL,
        latitude double precision NOT NULL,
        longitude double precision NOT NULL,
        accuracy_meters double precision NOT NULL,
        distance_from_office_meters double precision NOT NULL,
        allowed_radius_meters integer NOT NULL,
        is_within_allowed_radius boolean NOT NULL,
        success boolean NOT NULL,
        result_message text NOT NULL,
        source character varying(40) NOT NULL,
        attendance_log_id bigint,
        CONSTRAINT "PK_geo_punch_audits" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822074029_AddGeoPunchAudits') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260822074029_AddGeoPunchAudits', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822084506_AddLocationHistoryAccuracy') THEN
    ALTER TABLE employee_location_history ADD accuracy_meters double precision NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822084506_AddLocationHistoryAccuracy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260822084506_AddLocationHistoryAccuracy', '8.0.21');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822094642_AddEmployeeGpsSessions') THEN
    CREATE TABLE employee_gps_sessions (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        employee_id integer NOT NULL,
        session_id uuid NOT NULL,
        started_at_utc timestamp without time zone NOT NULL,
        last_update_at_utc timestamp without time zone NOT NULL,
        ended_at_utc timestamp without time zone,
        end_reason character varying(40),
        last_latitude double precision,
        last_longitude double precision,
        last_accuracy_meters double precision,
        last_distance_from_office_meters double precision,
        last_allowed_radius_meters integer,
        last_is_within_allowed_radius boolean,
        total_points integer NOT NULL DEFAULT 0,
        total_distance_meters double precision NOT NULL DEFAULT 0.0,
        average_accuracy_meters double precision,
        CONSTRAINT "PK_employee_gps_sessions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822094642_AddEmployeeGpsSessions') THEN
    CREATE INDEX "IX_employee_gps_sessions_employee_id_ended_at_utc" ON employee_gps_sessions (employee_id, ended_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822094642_AddEmployeeGpsSessions') THEN
    CREATE INDEX "IX_employee_gps_sessions_employee_id_started_at_utc" ON employee_gps_sessions (employee_id, started_at_utc);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822094642_AddEmployeeGpsSessions') THEN
    CREATE UNIQUE INDEX "IX_employee_gps_sessions_session_id" ON employee_gps_sessions (session_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822094642_AddEmployeeGpsSessions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260822094642_AddEmployeeGpsSessions', '8.0.21');
    END IF;
END $EF$;
COMMIT;

